In [1]:
import numpy as np


In [2]:
a = np.arange(0,12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
b = np.arange(12,24).reshape(4,3)
print(b)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [64]:
ba = np.arange(24,36).reshape(4,3)
ba

array([[24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [17]:
ab = np.arange(24,36).reshape(3,4)
ab

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [66]:
np.hstack((a,b,ba))

array([[ 0,  1,  2, 12, 13, 14, 24, 25, 26],
       [ 3,  4,  5, 15, 16, 17, 27, 28, 29],
       [ 6,  7,  8, 18, 19, 20, 30, 31, 32],
       [ 9, 10, 11, 21, 22, 23, 33, 34, 35]])

In [21]:
a+b

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [22]:
a-b

array([[-12, -12, -12],
       [-12, -12, -12],
       [-12, -12, -12],
       [-12, -12, -12]])

In [6]:
a*b

array([[  0,  13,  28],
       [ 45,  64,  85],
       [108, 133, 160],
       [189, 220, 253]])

In [7]:
b*a

array([[  0,  13,  28],
       [ 45,  64,  85],
       [108, 133, 160],
       [189, 220, 253]])

In [11]:
a/b

array([[0.        , 0.07692308, 0.14285714],
       [0.2       , 0.25      , 0.29411765],
       [0.33333333, 0.36842105, 0.4       ],
       [0.42857143, 0.45454545, 0.47826087]])

In [23]:
a@ab

array([[ 92,  95,  98, 101],
       [344, 356, 368, 380],
       [596, 617, 638, 659],
       [848, 878, 908, 938]])

In [8]:
c = np.arange(0,20).reshape(5,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
np.size(c)

20

In [10]:
#0 is rows
np.size(c,0)

5

In [26]:
#1 is col
np.size(c,1)

4

In [29]:
d = np.arange(5)
print(d)
d<2

[0 1 2 3 4]


array([ True,  True, False, False, False])

In [33]:
def exp(x):
    return x<3 or x>3
np.vectorize(exp)(a)

array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [40]:
r = a<9
print(a[r])
print(np.size(a[r]))

[0 1 2 3 4 5 6 7 8]
9


In [42]:
s = np.arange(24)
print(s)
print(np.sum(s<10))
print(np.sum(s[s<10]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
10
45


In [24]:
abc = np.arange(27).reshape(3,3,3)
abc

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [55]:
e = np.arange(40).reshape(4,10)
print(e)
print(e[e%2 == 0])
print(np.sum(e[e%2 == 0]))
id(e)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
380


2800819240192

In [57]:
print(id(a))
id(a.ravel)

2800818143680


2800764573088

In [53]:
id(a.flatten)

2800817590208

In [54]:
id(e.ravel)

2800764573088

In [58]:
#transpose the c
c.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [68]:
np.hstack((a,b,a))

array([[ 0,  1,  2, 12, 13, 14,  0,  1,  2],
       [ 3,  4,  5, 15, 16, 17,  3,  4,  5],
       [ 6,  7,  8, 18, 19, 20,  6,  7,  8],
       [ 9, 10, 11, 21, 22, 23,  9, 10, 11]])

In [67]:
np.vstack((a,b,a))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
np.dstack((a,b,ba))

array([[[ 0, 12, 24],
        [ 1, 13, 25],
        [ 2, 14, 26]],

       [[ 3, 15, 27],
        [ 4, 16, 28],
        [ 5, 17, 29]],

       [[ 6, 18, 30],
        [ 7, 19, 31],
        [ 8, 20, 32]],

       [[ 9, 21, 33],
        [10, 22, 34],
        [11, 23, 35]]])

In [71]:
np.split(a,2,axis = 0)

[array([[0, 1, 2],
        [3, 4, 5]]), array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [72]:
np.split(ab,2,axis=1)

[array([[24, 25],
        [28, 29],
        [32, 33]]), array([[26, 27],
        [30, 31],
        [34, 35]])]