In [1]:
import numpy as np

In [2]:
x=np.ones(10)
np.ones_like(x)= np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)


SyntaxError: can't assign to function call (<ipython-input-2-16d584064095>, line 2)

In [3]:
arr = np.arange(10)
arr[5:8]

array([5, 6, 7])

In [13]:
a=np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
b=np.array([[ 0, 2, 4], [ 6, 8, 10], [12, 14, 16]])
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [5]:
a=np.array([0, 1])
b= np.array([0, 2])
np.row_stack((a,b))


array([[0, 1],
       [0, 2]])

In [10]:
arr=[ 0.6095, -0.4938, 1.24 , -0.1357, 1.43 , -0.8469]
arr.sort() 
arr


[-0.8469, -0.4938, -0.1357, 0.6095, 1.24, 1.43]

In [11]:
b[0, :, :]

IndexError: too many indices for array

In [10]:
a=np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
b=np.array([[ 0, 2, 4], [ 6, 8, 10], [12, 14, 16]])
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [9]:
names = np.array(['Bob', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [14]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [12]:
a=np.array([[0, 1, 2 , 45], [3, 4, 5 , 7], [6, 7, 8 , 8]])
b=np.array([[ 0, 2, 4 , 47], [ 6, 8, 10 , 9], [12, 14, 16 , 7]])
np.dstack((a, b))


array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4],
        [45, 47]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10],
        [ 7,  9]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16],
        [ 8,  7]]])

In [8]:
a=np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
b=np.array([[ 0, 2, 4], [ 6, 8, 10], [12, 14, 16]])
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [45]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [15]:
a=np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
b=np.array([[ 0, 2, 4], [ 6, 8, 10], [12, 14, 16]])
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [16]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [17]:
a=np.array([0, 1])
b=np.array([0, 2])
np.column_stack((a,b))

array([[0, 0],
       [1, 2]])

In [18]:
arr = np.arange(10)
arr_slice = arr[5:8]
arr_slice[:] = 64
print(arr)


[ 0  1  2  3  4 64 64 64  8  9]


In [19]:
arr[9::-1]

array([ 9,  8, 64, 64, 64,  4,  3,  2,  1,  0])

In [20]:
np.zeros([[0,0,0], [0,0,0]])arr[9:-1:-1]

SyntaxError: invalid syntax (<ipython-input-20-5ee468f0b9b2>, line 1)

In [21]:
np.arange(9,-1,-1)-

SyntaxError: invalid syntax (<ipython-input-21-ac6edbfc18af>, line 1)

In [22]:
np.arange(9,-1)

array([], dtype=int32)

In [23]:
np.zeros([[0,0,0], [0,0,0]])

TypeError: 'list' object cannot be interpreted as an integer

In [24]:
np.empty((2,3,2))

array([[[1.24093928e-311, 2.42092166e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.46567317e+179]],

       [[5.89692433e-091, 7.26604192e-043],
        [4.29113955e-038, 1.65588256e-047],
        [6.99196247e+228, 5.63234836e-322]]])

In [41]:
a = np.array([[0, 1, 2 , 8],       [3, 4, 5 , 7],       [6, 7, 8 , 4]])
np.hsplit(a, 4)


[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]]), array([[8],
        [7],
        [4]])]

In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)


array([ 3, -1, -2,  0, 12, 10])

In [28]:
np.arange(9,-1,-1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
[9:-1:-1]

SyntaxError: invalid syntax (<ipython-input-29-65140810c728>, line 1)

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[9::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
arr[9:-1:-1]

array([], dtype=int32)