In [1]:
import numpy as np
arr = np.random.randn(7) * 5

In [2]:
arr

array([ 0.59342767, -2.85912899, -4.43526035,  7.78931438, -1.5500526 ,
        3.82236381, -6.62988698])

In [3]:
remainder, whole_part = np.modf(arr)

In [4]:
remainder

array([ 0.59342767, -0.85912899, -0.43526035,  0.78931438, -0.5500526 ,
        0.82236381, -0.62988698])

In [5]:
whole_part

array([ 0., -2., -4.,  7., -1.,  3., -6.])

In [9]:
arr

array([ 0.59342767, -2.85912899, -4.43526035,  7.78931438, -1.5500526 ,
        3.82236381, -6.62988698])

In [10]:
np.sqrt(arr)

C:\Users\Shahzad Ahsan\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([0.77034256,        nan,        nan, 2.79093432,        nan,
       1.95508665,        nan])

In [13]:
np.sqrt(arr, arr)

array([0.87769161,        nan,        nan, 1.67060897,        nan,
       1.39824413,        nan])

In [14]:
points = np.arange(-5, 5, 0.01)

In [15]:
 xs, ys = np.meshgrid(points, points)

In [16]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [17]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [18]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [19]:
result = [(x if c else y)for x, y, c in zip(xarr, yarr, cond)]

In [20]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [21]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [22]:
arr = np.random.randn(4, 4)

In [23]:
arr

array([[-0.75712265, -1.02153902, -0.96470076, -0.07651986],
       [-0.59114501,  1.08960241, -0.80197765, -0.98324256],
       [ 1.20149677,  0.926715  ,  1.5135242 , -0.81932978],
       [-1.12554889,  0.34359351, -0.65850028, -1.76661111]])

In [24]:
arr > 0

array([[False, False, False, False],
       [False,  True, False, False],
       [ True,  True,  True, False],
       [False,  True, False, False]])